### ISSUE TITLE
socketChannel.connect(remote);是否可能返回true

### ISSUE THREAD

**Issue by lixianmin** [jasonGeng88/blog#10]
SocketChannel在non-blocking mode下，是否有可能调用socketChannel.connect(remote);时直接链接成功就返回了true，如果是这样的话那后面注册的OP_CONNECT还能select()到嘛？

socketChannel.configureBlocking(false);
socketChannel.connect(remote);
socketChannel. register（ selector, SelectionKey. OP_ CONNECT| SelectionKey. OP_ READ）；

**Comment by jasonGeng88** [comment]
可以注册的。socketChannel.connect(remote); 做的只是进行了连接建立，
socketChannel. register 才是把 channel 放入队列中（这里的队列不是 select 获取就绪事件的队列），
而 select() 内部会轮询队列，进行最终的事件注册，至于怎么判断 io 流是否连接、可读可写，这是在内核态来判断的。

**Comment by lixianmin** [comment]
谢谢，解释的很仔细。nio好像是level trigger的，只要不处理，一直通知你


<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?iconUrl=http%3A%2F%2Fmail-online.nosdn.127.net%2F61fb4de4249c9d6b86d44150c93bdcc5.jpg&name=lixianmin&uid=example%40163.com&ftlId=3&items=%5B%22%E9%82%AE%E7%AE%B1%EF%BC%9Alixianmin%40live.cn%22%5D>
[http://mail-online.nosdn.127.net/61fb4de4249c9d6b86d44150c93bdcc5.jpg]
lixianmin
邮箱：lixianmin@live.cn


Signature is customized by Netease Mail Master<https://mail.163.com/dashi/dlpro.html?from=mail88>

在2018年06月24日 11:50，Jason<mailto:notifications@github.com> 写道：

可以注册的。socketChannel.connect(remote); 做的只是进行了连接建立，
socketChannel. register 才是把 channel 放入队列中（这里的队列不是 select 获取就绪事件的队列），
而 select() 内部会轮询队列，进行最终的事件注册，至于怎么判断 io 流是否连接、可读可写，这是在内核态来判断的。
