### ISSUE TITLE
关于JS this指向的问题

### ISSUE THREAD

**Issue by wangfpp** [jasonGeng88/blog#12]
![image](https://user-images.githubusercontent.com/35289556/46252557-ce4e9980-c49c-11e8-84e8-4428b0ac9f01.png)

**Comment by wangfpp** [comment]
obj2.a 等于3的啊

**Comment by jasonGeng88** [comment]
解释内容有误，已修正。
解释如下：

先获取obj2.obj1 -> 通过引用获取到obj1对象，再访问 obj1.foo -> 最后执行foo函数调用

这里调用链不只一层，存在obj1、obj2两个对象，那么隐式绑定具体会绑哪个对象。这里原则是获取最后一层调用的上下文对象，即obj1，所以结果显然是4（obj1.a）。
