### ISSUE TITLE
关于 redis 实现搜索引擎的提问

### ISSUE THREAD

**Issue by yisar** [jasonGeng88/blog#13]
![suo](http://wx4.sinaimg.cn/mw690/0060lm7Tly1fxi1xancd9j314o0r2tcw.jpg)

关于文章里面的，就是它最终交集产生了一个结果集，有提问如下：
得到这个结果集然后是根据id进行数据库查询吗？还是仍然在redis里又对应的数据，在redis里查询

**Comment by jasonGeng88** [comment]
抱歉，回复不及时。

看具体数据量和使用场景。redis 里可以放全量或部分热点数据，分页的场景，直接在数据库中查也没问题。

**Comment by yisar** [comment]
了解啦，阿里嘎多！
